<a href="https://colab.research.google.com/github/mfazeel798/ML-algorithms-KNN-LR-SVM-/blob/Branch1/HandWritting_Digit_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
#installing mnist to get data from the dataset liberary
#pip install python-mnist

SyntaxError: ignored

In [78]:
# importing assencial liberaries
import PIL as Image
from mnist import MNIST
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [79]:
# loading the mnist dataset
from tensorflow.keras.datasets import mnist
from matplotlib import pyplot as plt

# load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# summarize loaded dataset
print('Train: X=%s, y=%s' % (X_train.shape, y_train.shape))
print('Test: X=%s, y=%s' % (X_test.shape, y_test.shape))

Train: X=(60000, 28, 28), y=(60000,)
Test: X=(10000, 28, 28), y=(10000,)


In [80]:
# checking Dimentions
print( 'diemntion of trainy', y_train.ndim, 'diemntion of trainX', X_train.ndim)

diemntion of trainy 1 diemntion of trainX 3


In [81]:
# changineg shape of inputs to get them in to 2D array
X_train = X_train.reshape(-1,28*28)
X_test = X_test.reshape(-1,28*28)

In [82]:
# checking new shapes
print('Train: X=%s, y=%s' % (X_train.shape, y_train.shape))
print('Test: X=%s, y=%s' % (X_test.shape, y_test.shape))

Train: X=(60000, 784), y=(60000,)
Test: X=(10000, 784), y=(10000,)


In [83]:
print(X_train[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 198 182 247 241   0   0   0   0   

In [84]:
#transforming data in range 0 to 1
X_train = X_train/256
X_test = X_test/256

In [85]:
X_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [86]:
# building Multi_Layer_Perceptron Classifier Model
# model for neural network 
clf = MLPClassifier(solver = 'adam', activation = 'relu', hidden_layer_sizes=(64,64))

In [87]:
#training the model
clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [68]:
#predicting test data
y_pred = clf.predict(X_test)

In [69]:
#Confussion matrix to extract accuracy
acc = confusion_matrix(y_pred, y_test)
print(acc)

[[ 971    0    4    0    0    4    5    1    4    3]
 [   0 1124    1    0    0    0    2    2    1    2]
 [   0    3 1007    5    6    0    3    8    2    0]
 [   1    1    2  979    0    7    1    7    4    4]
 [   1    0    3    0  961    1    6    1    5   10]
 [   0    1    0   10    0  866    5    1    5    5]
 [   3    2    5    1    3    5  934    0    2    0]
 [   2    1    5    4    2    1    1 1000    4    6]
 [   2    3    4    4    2    6    1    2  944    2]
 [   0    0    1    7    8    2    0    6    3  977]]


In [70]:
#function to find accuracy from confussion_matrix cm
def accuracy(cm):
  digonal = cm.trace()
  elements = cm.sum()
  return digonal/elements

In [75]:
#accuracy of model (calling accuracy function)
print(accuracy(acc))

0.9763
